### PR TITLE
Pull sprint 2  Develop work into main

### PR DESCRIPTION
**Pull request by lmurdock12**
Working release of our sprint 2 work.

1. Contains work for the overall initial look and feel of the homepage and profiles.
2. Contains both the Create a tweet and follow another user functionality.

Please pull down the latest version of develop and test all functionality.

Review the code and make any comments that either need to be changed or say if everything looks good.

We can pull this into main once everyone agrees this look good.

### CODE REVIEW

**Review by bhball22 — APPROVED** [review]
They all Look amazing, but we will have to pre populate the database inside of Main don't we?

**Comment by lmurdock12** [comment]
> They all Look amazing, but we will have to pre populate the database inside of Main don't we?

Yes, once we pull in, someone will run the migration commands and push up the database file to main branch.

Will have to edit the gitignore in main to be able to push it up

**Comment by bhball22** [comment]
Perfect sounds great

**Review by natalie2by4 — APPROVED** [review]
Looks great to me

**Comment by lmurdock12** [comment]
Leaving develop branch open.

**Pull request merged**
