### PR TITLE
Add image tweet

### LINKED ISSUE #67: Add photo capabilities to tweets
Make tweets be able to be only photos, only text, or both.

- [x] Update Tweet Model
   - [x] Images
   - [x] can be NULL

### PR DESCRIPTION
**Pull request by lmurdock12**
Closes #67 

This allows a user to upload an image to a tweet if desired.

### CODE REVIEW

**Comment by natalie2by4** [comment]
So when I try to run it, it says "Operation Error at no such column: MainApp_tweet.tweet_image" but it also says that I had two unapplied migrations so I went back and did that whole process. When I tried to migrate it said this: "MainApp.Follow.following/Follow.user/Like.user/Tweet.tweet_creater/Admin.LogEntry.user was declared with lazy reference to 'MainApp.user', but app 'MainApp' doesn't provide model 'user'." and when I populated database is said: "There are no such table: MainApp_user". Every time I try to run the server after attempting to migrate it still says I have two unapplied migrations, so anyways there's some error when I try to do migrations and I'm not able to run and see it on my end.

**Comment by lmurdock12** [comment]
> So when I try to run it, it says "Operation Error at no such column: MainApp_tweet.tweet_image" but it also says that I had two unapplied migrations so I went back and did that whole process. When I tried to migrate it said this: "MainApp.Follow.following/Follow.user/Like.user/Tweet.tweet_creater/Admin.LogEntry.user was declared with lazy reference to 'MainApp.user', but app 'MainApp' doesn't provide model 'user'." and when I populated database is said: "There are no such table: MainApp_user". Every time I try to run the server after attempting to migrate it still says I have two unapplied migrations, so anyways there's some error when I try to do migrations and I'm not able to run and see it on my end.

Hmm.

First delete all your migration files in the migrations folder, and delete your db.sqlite file.

Rerun the makemigrations and migrate command and see if that fixes the problem.

**Comment by natalie2by4** [comment]
Fixed it, thanks

**Review by natalie2by4 — APPROVED** [review]
Works good!

**Review by bhball22 — APPROVED** [review]

**Pull request merged**
