### PR TITLE
Original setup for Twitter, this is just opening the webpages.

### PR DESCRIPTION
**Pull request by bhball22**
new file:   Account/__init__.py
	new file:   Account/__pycache__/__init__.cpython-38.pyc
	new file:   Account/__pycache__/urls.cpython-38.pyc
	new file:   Account/__pycache__/views.cpython-38.pyc
	new file:   Account/admin.py
	new file:   Account/apps.py
	new file:   Account/migrations/__init__.py
	new file:   Account/models.py
	new file:   Account/tests.py
	new file:   Account/urls.py
	new file:   Account/views.py
	new file:   Live_Scroll/__init__.py
	new file:   Live_Scroll/__pycache__/__init__.cpython-38.pyc
	new file:   Live_Scroll/__pycache__/urls.cpython-38.pyc
	new file:   Live_Scroll/__pycache__/views.cpython-38.pyc
	new file:   Live_Scroll/admin.py
	new file:   Live_Scroll/apps.py
	new file:   Live_Scroll/migrations/__init__.py
	new file:   Live_Scroll/models.py
	new file:   Live_Scroll/tests.py
	new file:   Live_Scroll/urls.py
	new file:   Live_Scroll/views.py
	new file:   Twitter
	new file:   src/__pycache__/__init__.cpython-38.pyc
	new file:   src/__pycache__/settings.cpython-38.pyc
	new file:   src/__pycache__/urls.cpython-38.pyc
	new file:   src/__pycache__/wsgi.cpython-38.pyc
	modified:   src/settings.py
	modified:   src/urls.py

### CODE REVIEW

**Comment by lmurdock12** [comment]
Good job it looks like everything works. 

A couple of things:

* Delete all of the __pycache__ files inside 'src' 'live_scroll' and 'account'..and recommit without those files
  * On my branch (which I will push on top of yours) a gitignore will be added so we will not have to worry about it in the future
* I would also suggest renaming 'Live_Scroll' into something like 'home or 'mainPage' or something like that since it is a more general name for everything that will be in that app (homepage with search and tweet functionalities

Push another commit to Initial_Website, and then we can pull it in

**Comment by bhball22** [comment]
The corrected files should be in place now, please look over for me.

**Review by lmurdock12 — APPROVED** [review]
Looks good...update the Twitter database file to Twitter_DB to make it a little more clear what this file was..pulling into develop now

**Comment by lmurdock12** [comment]
Should be merged. Initial_Website branch can be deleted on your local now

**Pull request merged**
